[package]
name = "potatonet-codegen"
version = "0.2.0"
authors = ["sunli"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.6"
syn = "1.0.11"
quote = "1.0.2"
itertools = "0.8.2"
